export default class CommonConstants {
  static readonly TAG_ABILITY: string = 'EntryAbility'
  static readonly TAG_HOME: string = 'HomePage'
  static readonly TAG_COMMON_UTILS: string = 'CommonUtils'
  static readonly TAG_CUSTOM: string = 'CustomDialogWidget'
  static readonly FILL_WIDTH: string = '100%'
  static readonly FULL_HEIGHT: string = '100%'
  static readonly DATE_YEAR: string = '年'
  static readonly DATE_MONTH: string = '月'
  static readonly DATE_DAY: string = '日'
  static readonly START_TIME: string = '1900-1-1'
  static readonly SELECT_TIME: string = '1990-1-1'
  static readonly BACK_MARGIN_LEFT: string = '7.2%';
  static readonly AVATAR_MARGIN_TOP: string = '5.5%';
  static readonly PERSONAL_MARGIN_TOP: string = '2.1%';
  static readonly COMMON_DIALOG_WIDTH: string = '93.3%';
  static readonly COMMA: string = '，';
  static readonly BACK_MARGIN_TOP: number = 19;
  static readonly BIGGER: number = 500;
  static readonly DY_OFFSET: number = -20;
  static readonly PLUS_ONE: number = 1;
  static readonly WEIGHT_ONE: number = 1;
  static readonly ONE_LINES: number = 1;
}