export default class CommonConstants {
  static readonly INDEX_MESSAGE: string = 'Index Page';
  static readonly SECOND_SRC_MSG: string = 'Index页面传来的数据';
  static readonly SECOND_URL: string = 'pages/SecondPage';

  static readonly SECOND_MESSAGE: string = 'Second Page';
  static readonly SECOND_SRC_PARAM: string = 'src';

  static readonly FULL_WIDTH: string = '100%';
  static readonly FULL_HEIGHT: string = '100%';

  static readonly FONT_SIZE: string = '38fp';
  static readonly PARAMS_FONT_SIZE: string = '20fp';

  static readonly BUTTON_FONT_SIZE: string = '16fp';
  static readonly BUTTON_WIDTH: string = '296vp';

  static readonly BUTTON_HEIGHT: string = '40vp';
  static readonly LAYOUT_HEIGHT: string = '140vp';

  static readonly PARAMS_OPACITY: number = 0.6;
}